// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test1', async function() {
    await driver.get("http://localhost:4200/")
    await driver.manage().window().setRect({ width: 1200, height: 645 })
    await driver.findElement(By.linkText("Реєстрація")).click()
    await driver.findElement(By.id("login")).click()
    {
      const element = await driver.findElement(By.id("login"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("login")).click()
    await driver.findElement(By.id("login")).sendKeys("nik.ermolenko@gmail.com")
    await driver.findElement(By.id("password1")).click()
    await driver.findElement(By.id("password1")).sendKeys("255106")
    await driver.findElement(By.id("password2")).click()
    await driver.findElement(By.id("password2")).sendKeys("255106")
    await driver.findElement(By.css("button")).click()
    await driver.close();
  })
})



